version: "3.8"

services:
  true_server:
    build: server/
    container_name: true_server
    networks:
      - foo
  fake_server:
    build: server/
    container_name: fake_server
    networks:
      - foo
    environment:
      - HIJACK=true
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - URL=lab.scc-net.tw
      - VALIDATION=http
      - SUBDOMAINS=true,fake,
    volumes:
      - "./swag/config:/config"
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    depends_on:
      - normal_server
      - fake_server

networks:
  foo:
    driver: bridge
