version: "3.8"

services:
  wg_split:
    container_name: wg_split
    image: zxc25077667/wg_split
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - SERVERURL=lab.scc-net.tw #optional
      - SERVERPORT=51820 #optional
      - PEERS=50 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - "./data/:/data/sslsplit/"
      - "./config:/config"
      - "/lib/modules:/lib/modules:ro"
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
